### ISSUE TITLE
Cleanup CMake based build

### ISSUE THREAD

**Issue by Mizux** [google/or-tools#1116]
# Introduction
All CMakeLists.txt need a deep refactoring about the dependencies management.

# Quick Survey
## Prebuilt vs Sources
There is two main way to consume a dependency,
1) Using some prebuilt binary

2) Integrating the dependency source to your project and compile them along the way.
    * show stopper: CMake targets which are **NOT** `IMPORTED` must form a closure on the install export set. (see `add_subdirectory()` limitation below)

## How to retrieve dependency Source ?
- using [git submodules](https://git-scm.com/docs/git-submodule)
- using CMake (>= 3.11.4) [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) module
- using the famous ExternalProjectAdd "submodule hack" (see [gtest doc](https://github.com/google/googletest/tree/master/googletest#incorporating-into-an-existing-cmake-project))

## How to retrieve Prebuilt
- Using the canonical way aka `find_package()` and it's the user responsibility to provide them...
- using ExternalProject_add ("regular") to build them.
  cons: do at build time not access to project stuff e.g. config.cmake...
- using ExternalProject_add "prebuilt hack" to compile/install deps in staging area then continue as regular `find_package()`
  see: https://github.com/Mizux/cmake-abseil/tree/install

## Three shades of ExternalProject usage
 AFAIK there is three way to use CMake `ExternalProject` module.
1) "regular"
```cmake
ExternalProject_Add(foo_project
  PREFIX "${CMAKE_BINARY_DIR}/dependencies/foo"
  GIT_REPOSITORY ...
  GIT_TAG "..."
  CMAKE_ARGS
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
```

2) "submodule hack" like gtest doc
see https://github.com/google/googletest/tree/master/googletest#incorporating-into-an-existing-cmake-project
(ed notice the configure/build/install command set to empty string -> only the "download/update step is performed") like a git submodule (aka Strategy 2)

3) "prebuilt hack" like "submobule hack" BUT build/install it in a staging area and add this staging to CMAKE_PREFIX_PATH
example: https://github.com/Mizux/cmake-abseil/tree/install

# Roadmap
* [x] Rework CMakeLists.txt in few Dependencies
  * [x] https://github.com/abseil/abseil-cpp (most on abseil-cpp HEAD)
  * [x] Split Cbc to follow new coin-or github layout (bye bye svn archive !)
    * [x] Move old Mizux/Cbc to Mizux/coinor-cbc and archive it.
    * [x] Add CMake support for each libraries (bye bye autotools)
    * [x] https://github.com/Mizux/CoinUtils
    * [x] https://github.com/Mizux/Osi
    * [x] https://github.com/Mizux/Clp
    * [x] https://github.com/Mizux/Cgl
    * [x] https://github.com/Mizux/Cbc
* [x] Rework Dependencies management (`install/find_package()` over `add_subdirectory()`)
  * see below for explanation why `add_subdirectory()` doesn't work...

# Misc
## Related PR
* PR #1019 `find_package()` everywhere, Tricks: you may have hidden `add_subdirectory()` inside FindFoo.cmake
  * nice trick since it will make the super build seen as a regular project
  * you can control what you want by CMAKE_PREFIX_PATH (i.e. find your custom FindFoo.cmake or the one in the system (good for distro maintainer))

## Related issues
* Missing install rule in abseil-cpp see: abseil/abseil-cpp/issues/111
* #732 CMake build support future
* #1025 CMake install rule not working
* #1159 OR-Tools CMake error
* #1169 OR-Tools Cbc sha1
* #1167 cbc -> coinor-cbc 
* https://github.com/coin-or/CoinUtils/issues/87 : Autotools does not support space in path and thus coin-or libraries too 
# Reference 
* [Don't package your libraries, write packagable libraries!](../../../CppCon/CppCon2018/blob/master/Presentations/dont_package_your_libraries_write_packagable_libraries/dont_package_your_libraries_write_packagable_libraries__robert_schumacher__cppcon_2018.pdf) by Robert Schumacher
  youtube: https://youtu.be/sBP17HQAQjk

## `add_subdirectory()` limitation
If you see this kind error
```
CMake Error: install(EXPORT "MyLibTargets" ...) includes target "MyLib" which requires target "deps" that is not in the export set.
```
Bravo ! you just figure out the limitation of add_subdirectory() vs regular cmake install dependencies ;)
add_subdirectory() add dependency targets not as `IMPORTED` targets so your export set must contains them (think of a graph closure of all target not imported) which you can't do unless hacking dependency source to modify the export set name...

note: bear in mind that until CMake 3.13, you can't add target to your super project export set.
> The install(TARGETS) command learned to install targets created outside the current directory.

src: https://cmake.org/cmake/help/v3.13/release/3.13.html#commands
note: simpler example here: https://github.com/Mizux/cmake-abseil

## Coin-OR integration
long story: coin-Cbc was on svn and I created the repo Mizux/cbc based on their "mono-repo" svn archive, then I added a CMake-based build.
Now, coin-OR use a one repo per library approach,  you can see on github they have split coin-or in several repo, so I moved it to mizux/coinor-cbc in order to fork coinor/Cbc to add (again) a CMake-Based build.

Here the list of my fork:
* https://github.com/Mizux/CoinUtils
* https://github.com/Mizux/Osi
* https://github.com/Mizux/Clp
* https://github.com/Mizux/Cgl
* https://github.com/Mizux/Cbc

Hope to soon send PR to coin-or maintainer, CMake patches/improvement are welcome !
warning: until I would consider my CMake integration "Stable/good enough" I'll heavily use rebase/fixup on my branch to keep an atomic final CMake single patch, which mean don't rely on SHA1 until release (i.e. PR is sent to coin-or)...

**Comment by Mizux** [comment]
dot file
```dot
@startdot
digraph Make {
	rankdir=BT;
	subgraph clusterPrerequisite {
		node [shape=box, style=rounded];
		CM [label="CMake", color=royalblue];
		SWIG [label="Swig\n(Unix)", color=chocolate];
		PY [label="Python\n(2.7,3.5,3.6)", color=gold];
		CM -> SWIG [arrowhead=none, style=invisible];
		SWIG -> PY [arrowhead=none, style=invisible];
		label = "Prerequisite";
	}
	subgraph clusterOR {
		node [shape=box,style=rounded];
		OR [label="C++", shape=component, style="rounded,filled,bold", color=royalblue, fillcolor=royalblue];
		OR_WPY [label="Python wrap", color=gold];
		OR_PY [label="Python\n(-DENABLE_PYTHON=ON)", style="rounded,filled,bold", color=gold, fillcolor=gold];
		OR -> OR_WPY [label="swig", color=chocolate];
		OR_WPY -> OR_PY [label="python", color=gold];
		OR -> OR_PY [label="python", color=gold];
		subgraph clusterDeps {
			node [shape=box,style=rounded];
			Z [label="Zlib\n(CMake)", color=royalblue];
			GF [label="GFlags\n(CMake)", color=royalblue];
			GL [label="GLog\n(CMake)", color=royalblue];
			PB [label="Protobuf\n(CMake)", color=royalblue];
			CBC [label="Cbc\n(CMake)", color=royalblue];
			SWIG_WIN [label="Swig\n(Windows)", color=chocolate];
			color=royalblue;
			label = "Dependencies\n(CMake subproject)";
		}
		Z -> OR [label="ExternalProject"];
		Z -> PB;
		PB -> OR [label="ExternalProject"];
		GF -> OR [label="ExternalProject"];
		GF -> GL;
		GL -> OR [label="ExternalProject"];
		Z -> CBC;
		CBC -> OR [label="ExternalProject"];
		subgraph clusterPackage {
			node [shape=component];
			PKG_CC [label=".deb Package", style="filled",	color=royalblue];
			PKG_PY [label="Pypi Package", style="filled",	color=gold];
			color=royalblue;
			label = "Package";
		}
		OR -> PKG_CC [label="WIP", style="dotted", color=dimgrey];
		OR_PY -> PKG_PY [color=gold];
		subgraph clusterEX {
			node [shape=box,style="rounded,dashed"];
			EX_CC [label="C++", color=royalblue];
			EX_PY [label="Python", color=gold];
			color=royalblue;
			label = "Examples";
		}
		OR -> EX_CC;
		OR_PY -> EX_PY [color=gold];
		color=royalblue;
		label = "OR-Tools (CMake)";
	}
}
@enddot
# vim tw:0
```

**Comment by Mizux** [comment]
Doc task move to #1200
