### ISSUE TITLE
Rework flags and logging management

### ISSUE THREAD

**Issue by Mizux** [google/or-tools#2201]
Now,
* `abseil-cpp` provide [`absl::flags`](https://github.com/abseil/abseil-cpp/tree/master/absl/flags) so we should migrate to it and drop Gflags.
* `google/glog` depends on `gflags/gflags` so we should build a custom version (like `google/protobuf`) which only rely on `absl::flags`
  note: Glog provide a way to disable gflags support but in this case we can't control glog behaviour on the command line anymore...

## Todo list
* [x] Custom version of Glog (logging.h) which only depends on absl::flags
  * [x] Get rid of google/glog dependency
* [x] Get rid of gflags/gflags dependency 
* [x] Fix bazel build
* [x] Fix CMake build
* [x] Fix Make build

## ref
Gflags is legacy ?: https://github.com/gflags/gflags/issues/307#issuecomment-655812036
Abseil-cpp logging status: https://github.com/abseil/abseil-cpp/issues/297
Protobuf custom logging: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/stubs/logging.h

**Comment by Mizux** [comment]
First version on master, may still need some cleanup...

Main difference between `Glog` and our custom version:
* Depends on `absl::flags` instead of `Gflags` (i.e. so we can drop `Gflags` deps)
* replace `GLOG_NO_ABBREVIATED_SEVERITIES` by `_MSC_VER`, since it **must** be define on windows only
* Windows
  * dlspec: when `OR_TOOLS_AS_DYNAMIC_LIB` is define (ie `-DBUILD_SHARED_LIBS=ON`), then internally we will use `OR_TOOLS_EXPORT` to select `dllexport` otherwise `dllimport` is chosen.
  see: https://github.com/google/or-tools/blob/master/ortools/base/logging_export.h
  * Glog use a second hierarchy in `src/windows` to maintain a windows specific version of headers etc... :sob: , here we try to merge both versions instead to maintain one file with a bunch of preprocessor (eg `#if defined(_MSC_VER)`)
