### ISSUE TITLE
CMake(Java): Add support for linux-aarch64 and darwin-aarch64

### ISSUE THREAD

**Issue by vmax** [google/or-tools#2538]
**What version of OR-Tools and what language are you using?**
Version: master
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**

SCIP

**What operating system (Linux, Windows, ...) and version?**
Linux (aarch64)

**What did you do?**
Tried running Java code utilizing `or-tools` on a machine with different architecture.

**What did you expect to see**

* OR-tools working
* A library similar to https://mvnrepository.com/artifact/com.google.ortools/ortools-linux-x86-64/ available for `linux-aarch64`

**What did you see instead?**

```
Exception in thread "main" java.lang.ExceptionInInitializerError
    ...
Caused by: java.lang.NullPointerException: Resource linux-aarch64/ was not found in ClassLoader jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc
    at java.base/java.util.Objects.requireNonNull(Objects.java:246)
    at com.google.ortools.Loader.getNativeResourceURI(Loader.java:25)
    at com.google.ortools.Loader.loadNativeLibraries(Loader.java:83)
   ...
    ... 3 more
```

**Anything else we should know about your project / environment**
May use https://github.com/multiarch/qemu-user-static to test aarch64 build in a docker.

EDIT(Mizux):
## ref
* https://mvnrepository.com/artifact/net.java.dev.jna/jna-platform
* https://github.com/java-native-access/jna/blob/cb31a0ad58484aa0d1935fa92f5cac6abcb1472c/build.xml#L522-L523
* https://github.com/java-native-access/jna/blob/cb31a0ad58484aa0d1935fa92f5cac6abcb1472c/build.xml#L551-L552

## ToDo List
* [x] `NATIVE_IDENTIFIER`: Add `linux-aarch64` support
* [x] `NATIVE_IDENTIFIER`: Add `darwin-aarch64` support
* [x] Update pom-full.xml.in
  * [x] Bump jna-platform to at least 5.7+ (darwin-aarch64)
  * [x] Update dependencies

**Comment by nurikk** [comment]
Hi, I'll be happy to help with testing if any dev builds are avaliable

**Comment by nurikk** [comment]
If you're here because of legacy VRP cp solver. Check this amazing project [Vehicle Routing Open-source Optimization Machine](https://github.com/VROOM-Project/vroom)

**Comment by liemteksun** [comment]
I'm also eagerly waiting for this as well

**Comment by liemteksun** [comment]
Thanks for finishing this
Any chance you have a binary build for linux-aarch64?
I tried to build it from source, but I think I might miss something and the build fails :(

thanks again
