### ISSUE TITLE
CMake(.Net): Add support for linux-arm64 and osx-arm64

### ISSUE THREAD

**Issue by Mizux** [google/or-tools#2724]
# Environment
## What version of OR-Tools and what language are you using?**
Version: master
Language: .Net

## What operating system (Linux, Windows, ...) and version?**
Linux: mandatory
Windows: nice to have
Mac: need "Apple Silicon" aka M1 support

# Additional context
May use https://github.com/multiarch/qemu-user-static to test aarch64 build in a docker.

## Reference:
[.Net RID Catalog](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#linux-rids)

## Todo list

* [x] `RUNTIME_IDENTIFIER`: Add linux-arm64 support
* [x] `RUNTIME_IDENTIFIER`: Add osx-arm64 support
* [x] Update Google.OrTools-full.csproj.in
  * [x] Update RID
  * [x] Update `ValidateRuntimePack` check
  * [x] Update `PackageReference` tags

## DevNote

* since makefile is now based on the CMake build it should be easier to integrate this feature.
* I've heard of user be able to hack our `dotnet.cmake` to make it works
* CMake infra should be easy to adapt, bassically you need to hack
https://github.com/google/or-tools/blob/f2e3e8e41f43fff5c57d8777efc43927f4daa894/cmake/dotnet.cmake#L34-L43
and `/p:Platform=` argument to make it dynamic
https://github.com/google/or-tools/blob/49b6301e1e1e231d654d79b6032e79809868a70e/cmake/dotnet.cmake#L194
https://github.com/google/or-tools/blob/49b6301e1e1e231d654d79b6032e79809868a70e/cmake/dotnet.cmake#L237
then it should be ok

For release I'll need to tweak
https://github.com/google/or-tools/blob/c48a7c437dbec8c7b5bf6d3361ec3d3bb179ca60/ortools/dotnet/Google.OrTools-full.csproj.in#L6 to add `osx-arm64` and `linux-arm64`

**Comment by andrea-cassioli-maersk** [comment]
Any progress on this issue?

**Comment by Mizux** [comment]
Yes and no,
* since makefile is now based on the CMake build it should be easier to integrate this feature.
* I've heard of user be able to hack to cmake to make it works
* CMake infra should be easy to adapt
https://github.com/google/or-tools/blob/49b6301e1e1e231d654d79b6032e79809868a70e/cmake/dotnet.cmake#L33-L41
and `/Platform` argument to make dynamic
https://github.com/google/or-tools/blob/49b6301e1e1e231d654d79b6032e79809868a70e/cmake/dotnet.cmake#L194
https://github.com/google/or-tools/blob/49b6301e1e1e231d654d79b6032e79809868a70e/cmake/dotnet.cmake#L237

then it should be ok
