### ISSUE TITLE
Fix Release scripts

### ISSUE THREAD

**Issue by Mizux** [google/or-tools#3150]
since the migration of Makefile to CMake lots of release scripts are broken:

So we need to Fix them and if possible get rid of Make and use a CMake based build

## Todo List (Blocking point):
* [x] SAT failure: waiting Googler support on Monday
* [x] linearization_level parameter doesn't work

### tools/doc:
* Notebook: **DONE**
* Python: **DONE** #3155
* Doxygen: **DONE**

Candidate: **10497**
### tools/release:
* Unix deliveries  "Manylinux" (Centos-7 based):
  * [x] .Net runtime package **DONE**
  * [x] Java runtime package **DONE**: (since the move to a CMake based build GPG_ARGS stuff need some refactor)
* MacOS deliveries:
  * [x] .Net package **DONE**
  * [x] Java package **DONE**
  * [x] Archive packages **DONE**
  * [x] Python [3.6, 3.10] packages **DONE** (need to update virtualvenv package)
* Windows:
  * [x] .Net package **DONE**
  * [x] Java package **DONE**
  * [x] Archive packages **DONE**
  * [x] Python [3.6, 3.7, 3.8, 3.9, 3.10] packages **DONE**

### tools/docker:
* Python:
  * [x] Python [3.6, 3.7, 3.8, 3.9, 3.10] Manylinux amd64 wheel **DONE**
  * [x] Python [3.6, 3.7, 3.8, 3.9, 3.10] Manylinux aarch64 wheel **NOT TESTED**
* Archives:
  * [x] alpine-edge **DONE**
  * [x] centos-7 LTS **DONE**
  * [x] centos-8 (Stream 8) **DONE** (https://github.com/dotnet/docs/issues/28438)
  * [x] ~~debian-10 Buster~~ **FAIL** (drop support, no gcc 10+ available)
  * [x] debian-11 Bulleyes **DONE**
  * [x] fedora-33 **DONE**
  * [x] fedora-34 **DONE**
  * [x] fedora-35 **DONE** (**/!\ dns issue on gLinux /!\**)
  * [x] opensuse-leap **DONE**
  * [x] ~~ubuntu-16.04 LTS~~ **FAIL** (drop support, no gcc 10+ available)
  * [x] ubuntu-18.04 LTS **DONE**
  * [x] ubuntu-20.04 LTS **DONE**
  * [x] ubuntu-21.10 Rolling **DONE**

**Comment by Mizux** [comment]
```mermaid
graph TD
A-->B
B-->C
C-->A
```
