### ISSUE TITLE
release v9.4: RC feedback

### ISSUE THREAD

**Issue by Mizux** [google/or-tools#3341]
ETA: 23th July 2022

Since the archive split, all scripts in tools/release should be updated to generate each artifacts.

# Current State
## Package managers:

| OS/Arch | .Net Runtime nupkg | Java Runtime .jar | Python [3.6,3.10] wheel |
|---|---|---|---|
| manylinux amd64<br>(manylinux2014) | Done  | Done | Done |
| manylinux aarch64 | Done  | Done | ToDo |
|   |   |   |   |
| macOS amd64 | Done  | Done | Done |
| macOS M1 | Done  | Done | Done |
|   |   |   |   |
| Windows amd64<br>(VS2019) | OK  | OK | OK |
| Windows amd64<br>(VS2022) | OK  | OK | OK |

.Net and Java will create a meta package depending on all runtimes packages

| Platform | Meta .Net nupkg | Meta Java .jar |
|---|---|---|
|  Generic | Done | Done |

## SDK Archives

| OS/Arch | C++ archive | .Net archive | Java archive | Python 3.10.5 archive |
|---|---|---|---|---|
| manylinux amd64 | ToDo  | ToDo | ToDo | NA |
| manylinux aarch64 | ToDo  | ToDo | ToDo | NA |
|   |   |   |   |   |
| macOS amd64 | ToDo  | ToDo | ToDo | ToDo |
| macOS M1 | ToDo  | ToDo | ToDo | ToDo |
|   |   |   |   |   |
| Windows VS2022 | ToDo  | ToDo | ToDo | ToDo |
| Windows VS2019 | ToDo  | ToDo | ToDo | ToDo |
|   |   |   |   |   |

# ToDo
* [x] Add a `build_delivery_manylinux_amd64.sh` script
* [x] Add a `build_delivery_manylinux_arm64.sh` script
* [x] Fix build_delivery_linux.sh
* [x] Fiix build_delivery_macos.sh
* [x] Fix build_delivery_windows.cmd

# Blocking Issues
## ARM64 dotnet binary (FIXED)
* arm64 `dotnet` cli can't run on `Centos:7 (aarch64)` or `manylinux2014_aarch64`.

Trace using a `quay.io/pypa/manylinux2014_aarch64:latest` as base image
```sh
$ objdump -p /lib64/libstdc++.so.6
...
20 0x00 0x0297f868 GLIBCXX_3.4.18
	GLIBCXX_3.4.17 
21 0x00 0x0297f869 GLIBCXX_3.4.19
	GLIBCXX_3.4.18
...
$ g++ --version
 g++ (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11)
$ dotnet --info
/usr/local/bin/dotnet: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/local/bin/dotnet)
/usr/local/bin/dotnet: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/local/bin/dotnet)
The command '/bin/sh -c dotnet --info' returned a non-zero code: 1
```
FIX: use of `quay.io/pypa/manylinux2014_aarch64:latest` which provide GLIBCXX 3.4.25
```sh
docker run --platform linux/arm64 --rm --init -it quay.io/pypa/manylinux_2_28_aarch64:latest
root@# yum update -y
root@# objdump -p /lib64/libstdc++.so.6 | grep GLIBCXX_3\.4\.2
...
27 0x00 0x0297f875 GLIBCXX_3.4.25
	GLIBCXX_3.4.24 
```

## Java decorator not supported (FIXED)
`@CanIgnoreReturnValue` didn't compile 
Decorator introduced by https://github.com/google/or-tools/commit/7e717e4293d990e5135177d6b9cfb67b34d07b88

note: to make it works we should depends on com.google.errorprone whch seems a pain to integrate to our pom.xml.in
ref: https://errorprone.info/docs/installation

## Bazel test broken on windows (FIXED)

use of `native.sh_test()` wrapper (in sat/ and graph/) didn't work on windows, prefer to use `native.cc_test()` which didn't have this issue.

note: migration from `cc_test` to `sh_test` in graph....
https://github.com/google/or-tools/commit/52e439d5eff0191034e6a070d49ae6ed795b68cc#diff-b1ca2b52b57b7ca1f4c83937f85de7d29a160265971b571069188b7bb5110d0c

## Windows Make test_cpp (FIXED)

Currently `make test_cpp` fail
see: https://github.com/google/or-tools/runs/7580164778?check_suite_focus=true

note: CMake provide a FindProtobuf builtin module so when using `find_dependency(Protobuf)` this one is use by CMake sample project. Unfortunately this one find our just built and and locally installed static protobuf library **BUT** it seems the module will add the compile definition `Protobuf_USE_DLLS` breaking everything...
fix: use `find_dependency(Protobuf CONFIG)`
todo(mizux): Inspect FindProtobuf.cmake and figure out why it unconditionnaly add the define when it shouldn't.

## Apple M1 can't use build CreateSigningApp (FIXED)

When trying to run CreateSigningApp this will crash on M1 (missing a `libhostfx.dylib` IIRC),
workaround: use `net6.0` TFM instead of `netcoreapp3.1`.

## OpenJDK 8/1.8 not available on Apple M1 (FIXED)

workaround: move to OpenJDK 11.0 available in homebrew

## Archive generation issue on Apple M1 (FIXED)

* Apple Make is 3.81 need at least 4.3
workaround: install make from homebrew
* Apple sed is not GNU so `sed -i -e  pattern` is treated as create output with extension `-e` instead of `-i` in-place and `-e pattern` as regexp pattern to parse...

workaround: try to use the homebrew gnu sed instead.
