### ISSUE TITLE
Migrate to abseil-cpp

### ISSUE THREAD

**Issue by Mizux** [google/or-tools#871]
# Description
Currently ortools provide its own custom [`base`](https://github.com/google/or-tools/tree/master/ortools/base) library but it should use [abseil-cpp](https://github.com/abseil/abseil-cpp) instead which is the official way to get Google C++ "basic" set of libraries.

Here the roadmap of [origin/abseil](https://github.com/google/or-tools/commits/abseil) branch:
## CCTZ Integration (DEPRECATED)
`cctz` is not needed anymore since abseil-cpp ship its own version.
(they have copy/paste the cctz code in https://github.com/abseil/abseil-cpp/tree/master/absl/time/internal/cctz)
note: debian already provide a `cctz` package...
1. [X] Patch `cctz` to add cmake install rule (google/cctz#82)
1. [X] Backport cmake install rule to `google/cctz` (cf google/cctz#83)
2. [X] Add `cctz` as third party deps in Makefile
3. [X] Revert `cctz` to Makefile (cctz is now integrated in abseil-cpp)

## Abseil-cpp Integration
1. [X] Patch `abseil-cpp` to add cmake intall rule (abseil/abseil-cpp#111)
1. [ ] Backport cmake install rule to `abseil/abseil-cpp` (abseil/abseil-cpp#182)
2. [X] Add `abseil-cpp` to Makefile based build on unix
2. [X] Add `abseil-cpp` to Makefile based build on windows
2. [X] Add `abseil-cpp` to CMake based build
3. [X] Port or-tools to abseil: **C++** Part (unix)
3. [x] Port or-tools to abseil: **C++** Part (windows)
3. [x] Port C++ example to abseil
4. [x] Port or-tools to abseil: **Python** Part
4. [x] Port Python example to abseil
5. [x] Port or-tools to abseil: **Java** Part
5. [x] Port Java example to abseil
6. [x] Port or-tools to abseil: **.Net** Part
6. [x] Port .Net example to abseil
7. [x] Update Python archive rules
7. [x] Update .Net runtime nuget package
7. [x] Update CC/Java/.Net archive rules

**Comment by Mizux** [comment]
note: You can follow current dev in `abseil` branch which will be forward merge to master once completion.

**Comment by Mizux** [comment]
Absl on windows need:
* absl::container compile fix -> https://github.com/abseil/abseil-cpp/pull/194
* Windows conformance alignment fix -> https://github.com/abseil/abseil-cpp/pull/196

We still have an issue on v15.8 about ortools/port/non_port.cc `DeleteFile()` method not found by the linker...
Appveyor-CI log
```shell
cl /EHsc /MD /nologo -nologo  /D__WIN32__ /DPSAPI_VERSION=1 /DNOMINMAX /DWIN32_LEAN_AND_MEAN=1 /D_CRT_SECURE_NO_WARNINGS /O2 -DNDEBUG /I. /Iortools/gen /I"dependencies\\install\\include" /I"dependencies\\install\\include" /DGFLAGS_DLL_DECL= /DGFLAGS_DLL_DECLARE_FLAG= /DGFLAGS_DLL_DEFINE_FLAG= /I"dependencies\\install\\include" /DGOOGLE_GLOG_DLL_DECL= /I"dependencies\\install\\include" /I"dependencies\\install\\include" /I"dependencies\\install\\include\\coin" /I"dependencies\\install\\include" /I"dependencies\\install\\include\\coin" /I"dependencies\\install\\include" /I"dependencies\\install\\include\\coin" /DUSE_CLP /I"dependencies\\install\\include" /I"dependencies\\install\\include\\coin" /I"dependencies\\install\\include" /I"dependencies\\install\\include\\coin" /DUSE_CBC /DUSE_GLOP /DUSE_BOP     objs\\binpacking_problem.obj  lib\\ortools.lib  /Febin\\binpacking_problem.exe
ortools.lib(linear_solver.obj) : error LNK2019: unresolved external symbol "struct util::Status __cdecl operations_research::DeleteFileA(class absl::string_view)" (?DeleteFileA@operations_research@@YA?AUStatus@util@@Vstring_view@absl@@@Z) referenced in function "protected: virtual bool __cdecl operations_research::MPSolverInterface::SetSolverSpecificParametersAsString(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?SetSolverSpecificParametersAsString@MPSolverInterface@operations_research@@MEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
bin\\binpacking_problem.exe : fatal error LNK1120: 1 unresolved externals
make.exe[1]: *** [bin/binpacking_problem.exe] Error 2
make.exe[1]: Leaving directory `C:/projects/or-tools-98u1n'
tools\make.exe: *** [test_cc_samples] Error 2
Command exited with code 2
```
src: https://ci.appveyor.com/project/lperron/or-tools-98u1n/build/job/ugrfir65gwt6kc0x
